### PR TITLE
added support for Inkscape 1.0-beta

### PR DESCRIPTION
**Pull request by dangrie158**
I just added support for Inkscape 1.0 Beta by fixing all deprecation warnings.

The only change that was necessary to fix errors with the previous version was to remove the first or second argument from horizontal or vertical moves from a Path respectively. This also broke the functions ```thin()``` and ```trim_svg_path()```. I first tried fixing them functionally, however I could not really find a case where they actually affected the output. furthermore, the code in ```trim_svg_path()``` seemed to be duplicated in ```thin()```.

Let me know if I overlooked something. I was not yet able to test backwards compatibility with 0.9X versions, however if this is a breaking change I would not recommend to merge the changes until 1.0 is final.

### CODE REVIEW

**Comment by Neon22** [comment]
Thanks Daniel,
I'll try to get to it soon. still doing some work in 0.92.4 and not ready to move to 1. 0 yet.

**Comment by johnflux** [comment]
I just tested this on :

Inkscape 1.0 (4035a4fb49, 2020-05-01)

And it caused Inkscape to just hang after pressing doing Extensions->Render->lasercut box  then press "Ok".

**Comment by johnflux** [comment]
I tried different sizes, and this time it generated an image.  But the sizes are all wrong.

I set the width to 130mm, for example, but the actual width (as measured by the inkscape ruler) is 33.65mm.

**Comment by johnflux** [comment]
It works well after reducing the number of tabs.  It hangs if the number of tabs is too high (it was 5 for the depth by default, but my depth was only 15mm.

**Comment by Neon22** [comment]
Thanks so much for your help with this. 
finally updated and tested and added to the inkscape extensions website.

**Pull request closed without merging**
